version: 2
jobs:
  install:
    docker:
      - image: circleci/node:11.10.1
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: node-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  build:
    docker:
      - image: circleci/node:11.10.1
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "yarn.lock" }}
      - run: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist/*

  lint:
    docker:
      - image: circleci/node:11.10.1
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "yarn.lock" }}
      - run: yarn lint

  test:
    docker:
      - image: circleci/node:11.10.1
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "yarn.lock" }}
      - run: yarn test:unit

  deploy:
    docker:
      - image: circleci/node:11.10.1
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: ~/project
      - run: yarn firebase deploy --token "$FIREBASE_TOKEN" --only hosting

workflows:
  version: 2
  integration:
    jobs:
      - install
      - build:
          requires:
            - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - build
            - lint
            - test
          filters:
            branches:
              only: master
