version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: node-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build

  lint:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "yarn.lock" }}
      - run: yarn lint

  test:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "yarn.lock" }}
      - run: yarn test:unit

workflows:
  version: 2
  build:
    jobs:
      - "build"
      - "lint"
      - "test"
