version: 2.1

commands:
  checkout_and_restore_cache:
    steps:
      - checkout
      - restore_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: v3-functions-dependencies-{{ checksum "yarn.lock" }}

executors:
  node:
    docker:
      - image: cypress/base:10.16.0
    working_directory: ~/app

jobs:
  install:
    executor: node
    steps:
      - checkout_and_restore_cache
      - run: yarn install
      - save_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: cd ./functions && yarn install
      - save_cache:
          key: v3-functions-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./functions/node_modules

  build:
    executor: node
    steps:
      - checkout_and_restore_cache
      - run: yarn build
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./dist

  lint:
    executor: node
    steps:
      - checkout_and_restore_cache
      - run: yarn lint

  test_unit:
    executor: node
    steps:
      - checkout_and_restore_cache
      - run: yarn test:unit --coverage
      - run: yarn codecov

  test_e2e:
    executor: node
    steps:
      - checkout_and_restore_cache
      - attach_workspace:
          at: ~/app
      - run:
          command: yarn firebase serve --only hosting -p 8080
          background: true
      - run: yarn cypress install
      - run: echo $SERVICE_ACCOUNT > ./serviceAccount.json
      - run: yarn test:e2e

  deploy:
    executor: node
    steps:
      - checkout_and_restore_cache
      - attach_workspace:
          at: ~/app
      - run: yarn firebase deploy --token "$FIREBASE_TOKEN" --only hosting

workflows:
  version: 2
  integration:
    jobs:
      - install
      - build:
          requires:
            - install
      - lint:
          requires:
            - build
      - test_unit:
          requires:
            - build
      - test_e2e:
          requires:
            - build
      - deploy:
          requires:
            - lint
            - test_unit
            - test_e2e
          filters:
            branches:
              only: master
