version: 2.1

commands:
  checkout_and_restore_cache:
    steps:
      - checkout
      - restore_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: v2-functions-dependencies-{{ checksum "yarn.lock" }}

executors:
  node:
    docker:
      - image: circleci/node:11.12.0
    working_directory: ~/app

jobs:
  install:
    executor: node
    steps:
      - checkout_and_restore_cache
      - run: yarn install --ignore-engines
      - save_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: cd ./functions && yarn install --ignore-engines
      - save_cache:
          key: v2-functions-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./functions/node_modules

  build:
    executor: node
    steps:
      - checkout_and_restore_cache
      - run: yarn build
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./dist

  lint:
    executor: node
    steps:
      - checkout_and_restore_cache
      - run: yarn lint

  test:
    executor: node
    steps:
      - checkout_and_restore_cache
      - run: yarn test:unit --coverage
      - run: yarn codecov

  deploy:
    executor: node
    steps:
      - checkout_and_restore_cache
      - attach_workspace:
          at: ~/app
      - run: yarn firebase deploy --token "$FIREBASE_TOKEN" --only hosting

workflows:
  version: 2
  integration:
    jobs:
      - install
      - build:
          requires:
            - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - build
            - lint
            - test
          filters:
            branches:
              only: master
